-- Creates the products table
DROP TABLE IF EXISTS products;
CREATE TABLE products (
    id BIGSERIAL PRIMARY KEY,
    uuid UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255),
    category VARCHAR(255),
    subcategory VARCHAR(255),
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    discount_percent DECIMAL(5, 2),
    final_price DECIMAL(10, 2) NOT NULL,
    rating DECIMAL(3, 2),
    review_count INT,
    stock_quantity INT,
    in_stock BOOLEAN,
    sku VARCHAR(100),
    barcode VARCHAR(100),
    weight_kg DECIMAL(10, 2),
    tags VARCHAR(255),
    image_url TEXT,
    thumbnail_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(50),
    featured BOOLEAN,
    length_cm DECIMAL(10, 2),
    width_cm DECIMAL(10, 2),
    height_cm DECIMAL(10, 2),
    free_shipping BOOLEAN,
    shipping_cost DECIMAL(10, 2),
    estimated_days INT
);